CREATE TABLE IF NOT EXISTS `ADA_TEAM_MEMBER` (
 `TEAM_MEMBER_ID` int(11) NOT NULL AUTO_INCREMENT,
 `USER` varchar(255),
 `TEAM_MEMBER_TYPE_ID` int(11),
 `PROJECT_ID` int(11),
 `START_DATE` datetime,
 `END_DATE` datetime,
 `CREATED_ON` datetime NOT NULL,
 `CREATED_BY` varchar(255) NOT NULL,
 `UPDATED_ON` datetime NOT NULL,
 `UPDATED_BY` varchar(255) NOT NULL,
 `IS_ACTIVE` tinyint(1) NOT NULL,
 PRIMARY KEY (`TEAM_MEMBER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
