CREATE TABLE IF NOT EXISTS `ADA_SECTION` (
 `SECTION_ID` int(11) NOT NULL AUTO_INCREMENT,
 `TITLE` varchar(255),
 `PROJECT_ID` int(11),
 `SECTION_TYPE_ID` int(11),
 `ORDER` int(11),
 `CREATED_ON` datetime NOT NULL,
 `CREATED_BY` varchar(255) NOT NULL,
 `UPDATED_ON` datetime NOT NULL,
 `UPDATED_BY` varchar(255) NOT NULL,
 `IS_ACTIVE` tinyint(1) NOT NULL DEFAULT 1,
 PRIMARY KEY (`SECTION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
