CREATE TABLE IF NOT EXISTS `ADA_DOCUMENT` (
  `DOCUMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `APPIAN_DOCUMENT_ID` int(11),
  `DOCUMENT_TYPE_ID` int(11),
  `RELATED_RECORD_TYPE_ID` int(11),
  `RELATED_RECORD_ID` int(11),
  `FOLDER_ID` int(11),
  `PROJECT_ID` int(11),
  `CREATED_ON` datetime NOT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `UPDATED_ON` datetime NOT NULL,
  `UPDATED_BY` varchar(255) NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL,
  PRIMARY KEY (`DOCUMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CALL IDEM_SP_DDL_UTIL_ADD_CONSTRAINT_IF_NOT_EXISTS('ADA_DOCUMENT', 'UNQ_DOCUMENT_APPIAN_DOCUMENT', 'UNIQUE', 'UNIQUE(`APPIAN_DOCUMENT_ID`)');
CALL IDEM_SP_DDL_UTIL_MODIFY_FIELD_IF_EXISTS ('ADA_DOCUMENT', 'IS_ACTIVE', 'tinyint(1) DEFAULT 1', 'UPDATED_BY');