CREATE TABLE IF NOT EXISTS `ADA_RECORD_TYPE` (
 `ID` int(11) NOT NULL AUTO_INCREMENT,
 `PROJECT_ID` int(11) DEFAULT NULL,
 `NAME` varchar(255) DEFAULT NULL,
 `TYPE` int(11) DEFAULT NULL,
 `DESCRIPTION` varchar(255) DEFAULT NULL,
 `SYNCED_RECORD` bit(1) DEFAULT NULL,
 `IS_ACTIVE` bit(1) DEFAULT 1,
 `CREATED_BY` varchar(255) DEFAULT NULL,
 `CREATED_ON` datetime(6) DEFAULT NULL,
 `MODIFIED_BY` varchar(255) DEFAULT NULL,
 `MODIFIED_ON` datetime(6) DEFAULT NULL,
 PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CALL IDEM_SP_DDL_UTIL_ADD_FIELD_IF_NOT_EXISTS ('ADA_RECORD_TYPE', 'UUID', 'varchar(255)', 'ID');