CREATE TABLE IF NOT EXISTS `ADA_CLIENT` (
 `CLIENT_ID` int(11) NOT NULL AUTO_INCREMENT,
 `NAME` varchar(255),
 `CREATED_ON` datetime NOT NULL,
 `CREATED_BY` varchar(255) NOT NULL,
 `UPDATED_ON` datetime NOT NULL,
 `UPDATED_BY` varchar(255) NOT NULL,
 `IS_ACTIVE` tinyint(1) NOT NULL,
 PRIMARY KEY (`CLIENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
