CREATE TABLE IF NOT EXISTS `ADA_OBJECT_ATTRIBUTE` (
 `OBJECT_ATTRIBUTE_ID` int(11) NOT NULL AUTO_INCREMENT,
 `OBJECT_ID` int(11) DEFAULT NULL,
 `ATTRIBUTE_TYPE_ID` int(11) DEFAULT NULL,
 `VALUE` LONGTEXT DEFAULT NULL,
 `IS_ACTIVE` bit(1) DEFAULT 1,
 `CREATED_BY` varchar(255) DEFAULT NULL,
 `CREATED_ON` datetime(6) DEFAULT NULL,
 `MODIFIED_BY` varchar(255) DEFAULT NULL,
 `MODIFIED_ON` datetime(6) DEFAULT NULL,
 PRIMARY KEY (`OBJECT_ATTRIBUTE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CALL IDEM_SP_DDL_UTIL_MODIFY_FIELD_IF_EXISTS ('ADA_OBJECT_ATTRIBUTE', 'VALUE', 'varchar(1000) DEFAULT NULL', 'ATTRIBUTE_TYPE_ID');
