CREATE TABLE IF NOT EXISTS `ADA_TASK_ENTITY` (
  `TASK_ENTITY_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TASK_ID` int(11) DEFAULT NULL,
  `PROJECT_ID` int(11) DEFAULT NULL,
  `ENTITY_TYPE_ID` int(11) DEFAULT NULL,
  `ENTITY_ID` int(11) DEFAULT NULL,
  `CREATED_ON` datetime NOT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `UPDATED_ON` datetime NOT NULL,
  `UPDATED_BY` varchar(255) NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL,
  PRIMARY KEY (`TASK_ENTITY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;