CREATE TABLE IF NOT EXISTS `ADA_PROJECT` (
  `PROJECT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(255) DEFAULT NULL,
  `CLIENT_NAME` varchar(255) DEFAULT NULL,
  `PRIVACY_RATING_ID` int(11) DEFAULT NULL,
  `PROJECT_STATUS_ID` int(11) DEFAULT NULL,
  `CURRENT_VERSION_ID` int(11) DEFAULT 0,
  `APPLICATION_PREFIX` varchar(255) DEFAULT NULL,
  `DESCRIPTION` varchar(4000) DEFAULT NULL,
  `START_DATE` date DEFAULT NULL,
  `END_DATE` date DEFAULT NULL,
  `LOGO_IMG_ID` int(11) DEFAULT NULL,
  `ENVIRONMENT_IMG_ID` int(11) DEFAULT NULL,
  `PARENT_FOLDER_ID` int(11) DEFAULT NULL,
  `DOCUMENT_FOLDER_ID` int(11) DEFAULT NULL,
  `IMAGE_FOLDER_ID` int(11) DEFAULT NULL,
  `CREATED_ON` datetime NOT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `UPDATED_ON` datetime NOT NULL,
  `UPDATED_BY` varchar(255) NOT NULL,
  `IS_ACTIVE` tinyint(1) DEFAULT 1,
  PRIMARY KEY (`PROJECT_ID`),
  KEY `ADA_FK_PROJECT_REF_STATUS` (`PROJECT_STATUS_ID`),
  KEY `ADA_FK_PROJECT_REF_PRIVACY_RATING` (`PRIVACY_RATING_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CALL IDEM_SP_DDL_UTIL_ADD_FIELD_IF_NOT_EXISTS ('ADA_PROJECT', 'PRIMARY_LOCALE', 'VARCHAR(255) DEFAULT NULL', 'DESCRIPTION`');
