-- Table structure for table `ADA_CUSTOM_SECTION`
--

CREATE TABLE IF NOT EXISTS `ADA_CUSTOM_SECTION` (
  `SECTION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(255) DEFAULT NULL,
  `PROJECT_ID` int(11) DEFAULT NULL,
  `CREATED_ON` datetime NOT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `UPDATED_ON` datetime NOT NULL,
  `UPDATED_BY` varchar(255) NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`SECTION_ID`),
  KEY `ADA_SECTION_PROJECT_ID_FK` (`PROJECT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
--
-- Constraints for dumped tables
--

--
-- Constraints for table `ADA_CUSTOM_SECTION`
--
ALTER TABLE `ADA_CUSTOM_SECTION`
  ADD CONSTRAINT `ADA_SECTION_PROJECT_ID_FK` FOREIGN KEY (`PROJECT_ID`) REFERENCES `ADA_PROJECT` (`PROJECT_ID`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
