CREATE TABLE IF NOT EXISTS `ADA_REF_OBJECT_TYPE` (
 `OBJECT_TYPE_ID` int(11) NOT NULL AUTO_INCREMENT,
 `PARENT_OBJECT_TYPE_ID` int(11) DEFAULT NULL,
 `VALUE` varchar(255) DEFAULT NULL,
 `XPATH` varchar(255) DEFAULT NULL,
 `IS_ACTIVE` bit(1) DEFAULT 1,
 `CREATED_BY` varchar(255) DEFAULT NULL,
 `CREATED_ON` datetime(6) DEFAULT NULL,
 `MODIFIED_BY` varchar(255) DEFAULT NULL,
 `MODIFIED_ON` datetime(6) DEFAULT NULL,
 PRIMARY KEY (`OBJECT_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;