CREATE TABLE IF NOT EXISTS `ADA_ROLE_MAP_CONFIG` (
 `ROLE_MAP_CONFIG_ID` int(11) NOT NULL AUTO_INCREMENT,
 `OBJECT_ID` int(11) DEFAULT NULL,
 `CONFIG_TYPE_ID` int(11) DEFAULT NULL,
 `GROUP_UUID` varchar(255) DEFAULT NULL,
 `IS_ACTIVE` bit(1) DEFAULT 1,
 `CREATED_BY` varchar(255) DEFAULT NULL,
 `CREATED_ON` datetime(6) DEFAULT NULL,
 `MODIFIED_BY` varchar(255) DEFAULT NULL,
 `MODIFIED_ON` datetime(6) DEFAULT NULL,
 PRIMARY KEY (`ROLE_MAP_CONFIG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
