CREATE TABLE IF NOT EXISTS `ADA_PROJECT` (
  `PROJECT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(255) DEFAULT NULL,
  `CLIENT_ID` int(11) DEFAULT NULL,
  `PRIVACY_RATING_ID` int(11) DEFAULT NULL,
  `PROJECT_STATUS_ID` int(11) DEFAULT NULL,
  `APPLICATION_PREFIX` varchar(255) DEFAULT NULL,
  `DESCRIPTION` varchar(4000) DEFAULT NULL,
  `START_DATE` date DEFAULT NULL,
  `END_DATE` date DEFAULT NULL,
  `PARENT_FOLDER_ID` int(11) DEFAULT NULL,
  `DOCUMENT_FOLDER_ID` int(11) DEFAULT NULL,
  `IMAGE_FOLDER_ID` int(11) DEFAULT NULL,
  `CREATED_ON` datetime NOT NULL,
  `CREATED_BY` varchar(255) NOT NULL,
  `UPDATED_ON` datetime NOT NULL,
  `UPDATED_BY` varchar(255) NOT NULL,
  `IS_ACTIVE` tinyint(1) DEFAULT 1,
  PRIMARY KEY (`PROJECT_ID`),
  KEY `ADA_FK_PROJECT_REF_STATUS` (`PROJECT_STATUS_ID`),
  KEY `ADA_FK_PROJECT_REF_PRIVACY_RATING` (`PRIVACY_RATING_ID`),
  KEY `ADA_FK_PROJECT_CLIENT` (`CLIENT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;


-- Constraints for table `ADA_PROJECT`
--
ALTER TABLE `ADA_PROJECT`
  ADD CONSTRAINT `ADA_FK_PROJECT_CLIENT` FOREIGN KEY (`CLIENT_ID`) REFERENCES `ADA_CLIENT` (`CLIENT_ID`),
  ADD CONSTRAINT `ADA_FK_PROJECT_REF_PRIVACY_RATING` FOREIGN KEY (`PRIVACY_RATING_ID`) REFERENCES `ADA_REFERENCE_DATA` (`ID`),
  ADD CONSTRAINT `ADA_FK_PROJECT_REF_STATUS` FOREIGN KEY (`PROJECT_STATUS_ID`) REFERENCES `ADA_REFERENCE_DATA` (`ID`);
COMMIT;
