
-- CREATE TABLE IF NOT EXISTS `AAA_MY_TABLE_1` (
--  `AAA_MY_TABLE_1_ID` int(11) NOT NULL AUTO_INCREMENT,
--  `NAME` varchar(255) NOT NULL,
--  `CREATED_ON` datetime NOT NULL,
--  `CREATED_BY` varchar(255) NOT NULL,
--  `UPDATED_ON` datetime NOT NULL,
--  `UPDATED_BY` varchar(255) NOT NULL,
--  `IS_ACTIVE` tinyint(1) NOT NULL,
--  PRIMARY KEY (`AAA_MY_TABLE_1_ID`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- CALL IDEM_SP_DDL_UTIL_ADD_FIELD_IF_NOT_EXISTS ('AAA_MY_TABLE_1', 'NAME2', 'VARCHAR(255) DEFAULT NULL', 'NAME');
